### ISSUE TITLE
Offset grid slice plots on the HMS-HMS grids

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#276]
Using the September 2023 grids, I'm trying to plot some population over the grid slices using `posydon.visualization.plot_pop.plot_popsyn_over_grid_slice`.

When doing so at 2Zsun, additional grid slices are plotted, which are not on the same grid of $\delta q = 0.05$ (see example below). Some even go above q=1. Other metallicities are fine.

Since this is the HMS-HMS grid, I expect all models to be the same grid slices. 

The models are always `initial_RLOF'. 
Is this an issue with the grid or the post-processing?
Has this been fixed already?

Example:
![grid_q_0 28](https://github.com/POSYDON-code/POSYDON/assets/14039563/35318bd7-1638-48a1-8ef9-d281a21f5c1a)

**Comment by mkruckow** [comment]
I think this is related to the reruns of columns, where the first model failed to be extrapolated from the ZAMS file.
The issue is the following: those have been corrected by starting from a different initial mass and first relaxing the mass to the desired one. But in this way, the directory names contain not the actual ZAMS masses, but the one, which we could extrapolate from the ZAMS models before the relaxation.
In case of initial RLO, those models usually fail on the synchronization step. As a consequence they don't have history.data files, hence the masses are recovered from the directory names instead, which are wrong on those cases.
Here a possible solution: renaming all the directories to the correct masses in all the reruns, where a ZAMS extrapolation failed. So long those are surely only initial RLO systems and shouldn't hurt to be in the grid.

**Comment by maxbriel** [comment]
I agree with them not affecting the grid, since it looks like most if not all are initial_RLO.

However, it currently messes up the plotting routine for plotting a population over a grid slice, since the limits are not accurately and the population is plotted on such an "empty" slice. I suggest we fix the plotting routine for this

**Comment by mkruckow** [comment]
OK, I have renamed the >1000 directories on Quest. Let's see whether there will be any left after getting a new data set.

**Comment by mkruckow** [comment]
@maxbriel , could you please check whether it is solved in the new grid version?
If it is fine, please close the issue. If it still happens, get back to me.

**Comment by maxbriel** [comment]
It took me a while to get around to this. But this is still an issue.
I checked with the `/v2/240718` version and got slices such as the one attached:
![image](https://github.com/user-attachments/assets/21816d61-25c0-4596-b85e-413dd2faceee)

This is currently being discussed on Slack in the reruns channel.

**Comment by mkruckow** [comment]
I hope, it will be gone in the next grid version, where @sgossage used a different way to relax the stars initially without changing any mass value.

**Comment by celiotine** [comment]
@maxbriel checking if this is still an issue?

**Comment by maxbriel** [comment]
Solved.
